# Generated by Django 5.1.11 on 2025-08-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('essay_type', models.CharField(choices=[('narrative', 'Narrative'), ('descriptive', 'Descriptive'), ('expository', 'Expository'), ('persuasive', 'Persuasive'), ('analytical', 'Analytical')], default='narrative', max_length=20)),
                ('content', models.TextField()),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='essay_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
