"""
Django settings for new_project project.

Generated by 'django-admin startproject' using Django 5.1.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
import environ
from dotenv import load_dotenv

import os

import os
OCRSPACE_API_KEY = os.environ.get("OCRSPACE_API_KEY")

load_dotenv()
BASE_DIR = Path(__file__).resolve().parent.parent

HF_TOKEN = os.getenv("HF_TOKEN")

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv("GOOGLE_CLIENT_ID"),
            'secret': os.getenv("GOOGLE_CLIENT_SECRET"),
            'key': ''
        }
    }
}

ZHIPU_API_KEY = os.getenv("ZHIPU_API_KEY")


env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Flutterwave Keys
FLW_PUBLIC_KEY = env("FLW_PUBLIC_KEY")
FLW_SECRET_KEY = env("FLW_SECRET_KEY")
FLW_ENCRYPTION_KEY = env("FLW_ENCRYPTION_KEY")
FLW_BASE_URL = "https://api.flutterwave.com/v3"  # same for test & live





EXCHANGE_API_KEY = os.getenv("EXCHANGE_API_KEY")
EXCHANGE_API_URL = "https://v6.exchangerate-api.com/v6"
DEFAULT_CURRENCY = "NGN"  

# LanguageTool API endpoint
LANGUAGETOOL_API = "http://localhost:8010/v2/check"

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


#letter

from django.core.management.utils import get_random_secret_key

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', get_random_secret_key())
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-key-change-me')

DEBUG = True  

ALLOWED_HOSTS_STR = os.environ.get('ALLOWED_HOSTS', '')

if ALLOWED_HOSTS_STR:
    # Parse environment variable
    ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS_STR.split(',') if h.strip()]
else:
    # Default hosts - ADD THEM ALL
    ALLOWED_HOSTS = [
        'eduprompt.com.ng',
        'www.eduprompt.com.ng',
        '.eduprompt.com.ng',  # Wildcard for ALL subdomains
        'eduprompt-t5x3.onrender.com',
        'localhost',
        '127.0.0.1',
        '[::1]',  # IPv6 localhost
    ]

# Always add Render's external hostname if available
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# NUCLEAR OPTION: Allow ALL hosts temporarily
ALLOWED_HOSTS.append('*')

# Remove duplicates
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))

# Debug print to logs
print("=" * 50)
print(f"ALLOWED_HOSTS: {ALLOWED_HOSTS}")
print(f"DEBUG: {DEBUG}")
print("=" * 50)

# ==============================
# CSRF TRUSTED ORIGINS
# ==============================
CSRF_TRUSTED_ORIGINS = [
    'https://eduprompt.com.ng',
    'https://www.eduprompt.com.ng',
    'https://*.eduprompt.com.ng',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.extend([
        f'https://{RENDER_EXTERNAL_HOSTNAME}',
        f'http://{RENDER_EXTERNAL_HOSTNAME}',
    ])

# Add your Render service URL
CSRF_TRUSTED_ORIGINS.extend([
    'https://eduprompt-t5x3.onrender.com',
    'http://eduprompt-t5x3.onrender.com',
])

# ==============================
# SECURITY SETTINGS
# ==============================
# IMPORTANT: This line FIXES the SSL header issue
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# DISABLE all security features temporarily
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False




ROOT_URLCONF = 'your_project_name.urls'

# ... rest of your settings (TEMPLATES, DATABASES, etc.)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'Eduprompt',
    'note',
    'quiz_generator',
    'essay',
    'project_writer',
    'grammar_checker',
    'allauth',
    'widget_tweaks',
    'users.apps.UsersConfig',
    'blog',
    'django_quill', 
    'ai_solver.apps.MathSolverConfig'
]

SITE_ID = 1

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

ROOT_URLCONF = 'new_project.urls'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'new_project.wsgi.application'
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[Eduprompt] "


import dj_database_url

db_url = os.environ.get("DATABASE_URL")
if not db_url:
    raise ValueError("DATABASE_URL environment variable is not set!")

DATABASES = {
    "default": dj_database_url.parse(db_url, conn_max_age=600, ssl_require=True)
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


CKEDITOR_UPLOAD_PATH = "uploads/"
LOGIN_URL = 'login'
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
]

SITE_ID = 1


# ✅ Modern allauth settings
ACCOUNT_SIGNUP_FIELDS = ["email", "password1", "password2"]
ACCOUNT_LOGIN_METHODS = {"email"}  # must be a set, not a list

# Email verification (optional, adjust to your needs)
ACCOUNT_EMAIL_VERIFICATION = "optional"   # "none" | "optional" | "mandatory"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"

# Redirect after login/signup
LOGIN_REDIRECT_URL = "/"
ACCOUNT_SIGNUP_REDIRECT_URL = "/"


# 🚀 Silence old warnings (safety, though not needed after cleanup)
SILENCED_SYSTEM_CHECKS = ["account.W001"]




CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "Full",  # or customize toolbar
        "height": 300,
        "width": "100%",
        "extraPlugins": "uploadimage",  # allow image uploads
    }
}

# settings.py
LOGIN_URL = "/?show_login=true"
LOGIN_REDIRECT_URL = "/"          # After login

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "prospereze12345@gmail.com"
EMAIL_HOST_PASSWORD = os.getenv("GMAIL_APP_PASSWORD")  # safe in Render env

DEFAULT_FROM_EMAIL = "EduPrompt <prospereze12345@gmail.com>"




# Add your custom domain here:
ALLOWED_HOSTS = [
    "eduprompt-t5x3.onrender.com", 
    "127.0.0.1", 
    "localhost",
    "eduprompt.com.ng",           # ADD THIS
    "www.eduprompt.com.ng",       # ADD THIS
    ".eduprompt.com.ng",          # ADD THIS (wildcard for all subdomains)
]

CSRF_TRUSTED_ORIGINS = [
    "https://eduprompt-t5x3.onrender.com",
    "https://eduprompt.com.ng",    # ADD THIS
    "https://www.eduprompt.com.ng", # ADD THIS
]
