"""
Django settings for new_project project.

Generated by 'django-admin startproject' using Django 5.1.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
import environ
from dotenv import load_dotenv

import os



load_dotenv()
BASE_DIR = Path(__file__).resolve().parent.parent

HF_TOKEN = os.getenv("HF_TOKEN")

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv("GOOGLE_CLIENT_ID"),
            'secret': os.getenv("GOOGLE_CLIENT_SECRET"),
            'key': ''
        }
    }
}

ZHIPU_API_KEY = os.getenv("ZHIPU_API_KEY")


env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Flutterwave Keys
FLW_PUBLIC_KEY = env("FLW_PUBLIC_KEY")
FLW_SECRET_KEY = env("FLW_SECRET_KEY")
FLW_ENCRYPTION_KEY = env("FLW_ENCRYPTION_KEY")
FLW_BASE_URL = "https://api.flutterwave.com/v3"  # same for test & live





EXCHANGE_API_KEY = os.getenv("EXCHANGE_API_KEY")
EXCHANGE_API_URL = "https://v6.exchangerate-api.com/v6"
DEFAULT_CURRENCY = "NGN"  

# LanguageTool API endpoint
LANGUAGETOOL_API = "http://localhost:8010/v2/check"

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


#letter
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-aga@)uqd^8!kaqswudioc_lr6mh3#2=33qo=b#52a9r3#^np1!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'Eduprompt',
    'note',
    'quiz_generator',
    'essay',
    'ai_solver',
    'project_writer',
    'grammar_checker',
    'allauth',
    'widget_tweaks',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'users.apps.UsersConfig',
    'blog',
    'django_quill', 

    
]
SITE_ID = 1



LOCALE_PATHS = [
    BASE_DIR / 'locale',  # where translation files will be stored
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'new_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'new_project.wsgi.application'
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[Eduprompt] "
DEFAULT_FROM_EMAIL = "no-reply@Eduprompt.com.ng"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


CKEDITOR_UPLOAD_PATH = "uploads/"
LOGIN_URL = 'login'
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
]

SITE_ID = 1


# ✅ Modern allauth settings
ACCOUNT_SIGNUP_FIELDS = ["email", "password1", "password2"]
ACCOUNT_LOGIN_METHODS = {"email"}  # must be a set, not a list

# Email verification (optional, adjust to your needs)
ACCOUNT_EMAIL_VERIFICATION = "optional"   # "none" | "optional" | "mandatory"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"

# Redirect after login/signup
LOGIN_REDIRECT_URL = "/"
ACCOUNT_SIGNUP_REDIRECT_URL = "/"


# 🚀 Silence old warnings (safety, though not needed after cleanup)
SILENCED_SYSTEM_CHECKS = ["account.W001"]




CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "Full",  # or customize toolbar
        "height": 300,
        "width": "100%",
        "extraPlugins": "uploadimage",  # allow image uploads
    }
}
from django.urls import reverse_lazy

LOGIN_URL = 'login'               # must match the name of a URL
LOGIN_REDIRECT_URL = "/"          # After login
LOGOUT_REDIRECT_URL = "/"         # After logout

# Example email backend for testing in dev
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@example.com'
               # After logout

# 👇 Custom domain for password reset emails
DEFAULT_DOMAIN = "127.0.0.1:8000"


# For development: emails printed in console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'



EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "prospereze12345@gmail.com"
EMAIL_HOST_PASSWORD = "qqkd jwcg enui cxmb"  
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
